sanity-io/sanity-astro

- package-lock.json
- packages/sanity-astro/package.json
- packages/sanity-astro/studio/StudioComponent.tsx
It seems like removing the `useTheme` hook to style the Studio container solves the 
```
interleave.js:11 Uncaught (in promise) SyntaxError: The requested module '/node_modules/shallowequal/index.js?v=f34bacbe' does not provide an export named 'default' (at interleave.js:11:36)
```
bug. This PR also removes the Styled Components peer dependency since that broke installations without the `--legacy-peer-deps` flag.
> Remove preloaded theme support

- apps/example/astro.config.mjs
- packages/sanity-astro/index.ts
- packages/sanity-astro/vite-plugin-sanity-studio.ts
The logic in the plugin loading required everyone to set the `studioBasePath` and add `sanity.config.ts`. The intention with this feature was to be optional.
This PR makes `studioBasePath` the “switch” by skipping adding the studio route if not set. I also centralized the error handling so it's a bit easier to reason about when the plugin tries to load the Studio or not. I also replaced a console warning with an Error if `studioBasePath` is set without a config file so that folks are more likely to notice something wrong.
> Feat: Make studio embedding optional

- apps/example-ssr/src/components/InternalLink.astro
- apps/example-ssr/src/components/NewsBar.jsx
- apps/example-ssr/src/components/SanityImage.astro
- apps/example-ssr/src/layouts/Layout.astro
- apps/example-ssr/src/pages/index.astro
- apps/example-ssr/src/pages/posts/[slug].astro
- apps/example/sanity.config.ts
- apps/example/src/components/InternalLink.astro
- apps/example/src/components/NewsBar.jsx
- apps/example/src/components/SanityImage.astro
- apps/example/src/layouts/Layout.astro
- apps/example/src/pages/index.astro
- apps/example/src/pages/posts/[slug].astro
- packages/sanity-astro/README.md
- packages/sanity-astro/index.ts
- packages/sanity-astro/studio/StudioComponent.tsx
- packages/sanity-astro/studio/usePrefersColorScheme.ts
- packages/sanity-astro/studio/useTheme.ts
- packages/sanity-astro/vite-plugin-sanity-client.ts
- packages/sanity-astro/vite-plugin-sanity-studio.ts
I started digging into https://github.com/sanity-io/sanity-astro/issues/59 and noticed that we could simplify the developer experience of this plugin and bring it closer to the Astro conventions:
* Removes the `useSanityClient()` hook. It caused problems when imported into client-side non-Astro files
* Introduces the `import { sanityClient } from 'sanity:client'` pattern, which works across `.astro` and non-`.astro` files
* Adds a JSX component with client-side data-fetching to the example
This is a breaking change since it deprecates the `useSanityClient` hook.
Some commits in this PR intentionally don't follow Vite plugin conventions in favor of adopting Astro integration conventions.
I _think_ I managed to include typing support for the modules, but that is a thing to double-check.
> feature!: Add support for third-party templating languages

- apps/example-ssr/src/env.d.ts
- apps/example/src/env.d.ts
- packages/sanity-astro/package.json
Hello team 🏄🏻 !
tldr;
This PR intends to fix the issue where importing from `sanity:client` throws an error, despite the correct triple-slash directive in `env.d.ts`. Should resolve #135.
More info:
I've realised, that `/// <reference types="@sanity/astro/module" />` did not actually link to anywhere when doing a `⌘ + Click`. 
Upon this discovery, I've noticed, that on `v2.2.0` the export pointing to the `module.d.ts` file has been removed, leading to a reference to nowhere and the files contents not being imported.
I've forked the package and linked to it locally, validating that once the export is added back it works.
> fix(module): add back missing module export

- apps/example/astro.config.mjs
- apps/example/package.json
- packages/sanity-astro/README.md
- packages/sanity-astro/src/studio/studio-route.astro
- packages/sanity-astro/src/vite-plugin-sanity-studio.ts
We unnecessarily require folks to set their Astro sites to `hybrid` or `server`. This PR adds a static path setting to the embedded studio route to eliminate the `prerender = false` declaration and thus, the need to set `output: 'hybrid'|'server'`.
> feat!: Remove requirement for hybrid/server rendering

- packages/sanity-astro/src/studio/studio-route.astro
Fixes the built-in Studio route so it doesn't pre-render, but goes into "spa-mode"
> fix: studio route should not be prerendered as it's a dynamic spa route

- packages/sanity-astro/src/index.ts
- packages/sanity-astro/src/vite-plugin-sanity-client.ts
- packages/sanity-astro/src/vite-plugin-sanity-studio.ts
I had a little bit of trouble understanding what options/configs were passed
where and why, so now I've more clearly separated the client config options and
the `studioBasePath` option. I've also adjusted the return types of the Vite
Plugin factory functions to make TypeScript happy.
> refactor: improve internal types

- .github/workflows/prettier.yml
- .prettierignore
This way you don't accidentally format it if you run Prettier manually on the codebase.
> chore: .prettierignore CHANGLELOG.md

- package-lock.json
- packages/sanity-astro/package.json
- packages/sanity-astro/src/vite-plugin-sanity-client.ts
Before this change, non-JSON ClientConfig like the `ResolveStudioUrl` you can pass to `stega.studioUrl` would be serialised away. Now, we use `serialize-javascript` to serialise the config into a superset of JSON that preserves functions.
Note: Installing the dependency automatically adjusted the version range of `dependency.@sanity/client` to match the one in `peerDependencies`.
> fix: allow non-JSON ClientConfig

- package-lock.json
- packages/sanity-astro/README.md
- packages/sanity-astro/package.json
- packages/sanity-astro/src/visual-editing/index.ts
- packages/sanity-astro/src/visual-editing/visual-editing.astro
This repo doesn't have an app to test this component with yet, but I've tested it in the `astro` app in `visual-editing` by
1. Building this package locally
2. `npm pack` to produce a tarball
3. Checking out this branch: https://github.com/sanity-io/visual-editing/pull/1545/files in `visual-editing`
4. Installing that `.tgz` file
```
-    "@sanity/astro": "^3.0.1",
+    "@sanity/astro": "file:../../../sanity-astro/packages/sanity-astro/sanity-astro-3.0.1.tgz",
```
5. Using `VisualEditing` from the pacakage
```
-import {VisualEditing} from '@sanity/visual-editing/astro'
+import {VisualEditing} from '@sanity/astro/visual-editing'  
```
> feat: add VisualEditing component

- packages/sanity-astro/src/visual-editing/visual-editing-component.tsx
- packages/sanity-astro/src/visual-editing/visual-editing.astro
The previous code didn't work. You can't pass a callback to a React component that way in an `.astro` file. Therefore, we need an extra wrapper for this island.
> fix(visual-editing): avoid using JSX in the .astro file

- packages/sanity-astro/README.md
`@sanity/client`, `@sanity/visual-editing` and `sanity` are now peer dependencies of this package.
> docs: update manual installation dependency list

- .prettierignore
Otherwise, Renovatebot will open a new Prettier PR every single time it has updated some dependencies.
---
I looked into if it was possible to add this ignore rule to https://github.com/sanity-io/prettier-config so it would apply to all our repos automatically, but it doesn't look like that is possible.
> chore: .prettierignore pnpm-lock.yaml

- apps/movies/src/env.d.ts
- apps/movies/src/layout.astro
- apps/movies/src/load-query.ts
- packages/sanity-astro/README.md
Hopefully, this avoids any confusion. The env var needs the `PUBLIC_` prefix to be used in the layout.
> docs: prefix env var with PUBLIC_

- package.json
- pnpm-lock.yaml
Transitive dependencies `braces` and `ws` currently fail our builds:
> chore: fix failing audits

- packages/sanity-astro/src/studio/studio-component.tsx
The semicolon was added after the studio component, causing an issue with the positioning.
> fix: remove wild semicolon in StudioComponent JSX

- apps/example-ssr/package.json
- apps/movies/package.json
- packages/sanity-astro/package.json
- packages/sanity-astro/src/index.ts
- pnpm-lock.yaml
Before this change, passing nothing to `sanity()` would result in the integration crashing because of the attempt to destructure `studioBasePath` from `undefined`. Now, we guard against this scenario be defaulting to `{}` if no config is passed, and by not using destructuring to pick and omit `studioBasePath` from the config.
> fix: allow integration options to be undefined

- packages/sanity-astro/src/index.ts
- pnpm-lock.yaml
As described in issue #210 , @sanity/astro@3.1.4 will cause Astro to crash if a full protocol-domain url is configured for `studioBasePath`.
That would properly be done any time a separate, non-embedded Studio is used for the app, whether Presentation is engaged or not.
This PR fixes the problem by simply avoiding the attempt to enter an Astro route, when it iswould be improper because the path is not within the app.
> fix: error out if studioBasePath looks like an absolute URL

- apps/example/astro.config.mjs
- apps/example/package.json
- packages/sanity-astro/package.json
- packages/sanity-astro/src/index.ts
- packages/sanity-astro/src/studio/studio-component.tsx
- packages/sanity-astro/src/studio/studio-route-hash.astro
- packages/sanity-astro/src/vite-plugin-sanity-studio-hash-router.ts
- pnpm-lock.yaml
Fixes #232, allows embedding a studio with a hash router, similar to the `next-sanity` feature:
```ts
// app/studio/page.tsx
import {NextStudio} from 'next-sanity'
import config from 'sanity.config'
export default function StudioPage() {
return <NextStudio config={config} history="hash" />
}
```
If it works well it could be a good default in a future major.
> feat: support embedding studios without ssr

- apps/movies/package.json
- packages/sanity-astro/README.md
- packages/sanity-astro/package.json
- packages/sanity-astro/src/index.ts
- packages/sanity-astro/src/visual-editing/visual-editing-component.tsx
- pnpm-lock.yaml
The fix in #301 proved to be too reliant on package manager behavior for the `optimizeDeps` to "take". By moving `@sanity/visual-editing` from a peer dep to a direct one, the `optimizeDeps.include` rules consistently apply in pnpm v9+, npm v10+ and yarn v4+.
Adding `react-is` to peer deps also ensures the `npx astro add` command picks it up, and solves warnings in yarn v4.
Finally, the `portal` prop added to `<InternalVisualEditing>` fixes a TS error there. `portal={true}` is the default value under the hood.
> fix: make visual editing a direct dependency
